### ISSUE TITLE
python dependencies

### ISSUE THREAD

**Issue by calkan** [mills-lab/vapor#1]
./ vapor
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sklearn' distribution was not found and is required by VaPoR

however:
sudo apt install python-sklearn
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-sklearn is already the newest version (0.17.0-4).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

sudo apt install python-sklearn-lib 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-sklearn-lib is already the newest version (0.17.0-4).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

ls /usr/lib/python2.7/dist-packages/sklearn/
base.py           cluster               discriminant_analysis.py   feature_selection  isotonic.pyc                   lda.pyc             multiclass.py    pipeline.pyc           setup.py
base.pyc          covariance            discriminant_analysis.pyc  gaussian_process   _isotonic.x86_64-linux-gnu.so  learning_curve.py   multiclass.pyc   preprocessing          setup.pyc
_build_utils.py   cross_decomposition   dummy.py                   grid_search.py     kernel_approximation.py        learning_curve.pyc  naive_bayes.py   qda.py                 svm
_build_utils.pyc  cross_validation.py   dummy.pyc                  grid_search.pyc    kernel_approximation.pyc       linear_model        naive_bayes.pyc  qda.pyc                tests
calibration.py    cross_validation.pyc  ensemble                   __init__.py        kernel_ridge.py                manifold            neighbors        random_projection.py   tree
calibration.pyc   datasets              externals                  __init__.pyc       kernel_ridge.pyc               metrics             neural_network   random_projection.pyc  utils
__check_build     decomposition         feature_extraction         isotonic.py        lda.py                         mixture             pipeline.py      semi_supervised

**Comment by calkan** [comment]
poke @remills

**Comment by xuefzhao** [comment]
Hi, 

can you first try 'pip install scikit-learn' to install sklearn, and then try vapor to see if the same problem still exits?

**Comment by calkan** [comment]
It worked after that, and a few updates and links. At least the help menu is printed now. And python is bullshit. @remills
